
# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from hooks.py and the example nodes in
# `src/pipelines/`
# Documentation for this file format can be found in "Parameters"
# Link: https://kedro.readthedocs.io/en/stable/04_kedro_project_setup/02_configuration.html#parameters
example_test_data_ratio: 0.2
example_num_train_iter: 10000
example_learning_rate: 0.01

important_covs: ['Gender', 'Age', 'Race USA Category', 'Ethnicity USA Category', 'PMI', 'num_peaks', 'num_raw_reads', 'RelCC', 'post_rmdup_reads', 'aln_rate', 'post_atrim', 'too_short_post_atrim', 'RiP%', 'reads_in_peaks', 'SSD', 'post_aln_reads', 'uniq_aln_rate', 'IGV_quality', 'frac_pcr_dups', 'NIDA_seq_batch']

left_out_covs: ['Additional_Notes', 'Additional_Notes_1', 'Barcode_ID', 'COD', 'ChIP-Seq ID', 'Clinical_Dx', 'Comments', 'Diagnosis', 'Duplicate', 'Frozen Tissue Sent', 'ID', 'ID_on DM List', 'RiBL%', 'Sample_ID_on_Submission_Form', 'Submission_Project_Number', 'Tissue Code', 'Tissue_Code_on_DM_List ', 'Triplicate ', 'Used in ChIP-Seq Analysis', 'genome', 'mark', 'replicate_set', 'sample', 'sample.1', 'use_for_analysis']

cc_col: "case_control_status"